### ISSUE TITLE
udp: calling net.Dial causes runtime panic

### ISSUE THREAD

**Issue by deadprogram** [tinygo-org/net#9]
When attempting to run the `examples/ntpclient` with the latest `net` and the matching `drivers` repo branch, on this line of code:

```go
conn, err := net.Dial("udp", ntpHost)
```

I get the following error:

```
panic: runtime error at 0x10013bbf: slice smaller than array
```

**Comment by deadprogram** [comment]
Same error with the `examples/tcpecho` but on this line of code:

```go
l, err := net.Listen("tcp", port)
```

```
panic: runtime error at 0x10013dff: slice smaller than array
```

**Comment by deadprogram** [comment]
Also on the `webserver` example:

```go
err = http.ListenAndServe(port, nil)
```

```
panic: runtime error at 0x1000aa1f: slice smaller than array
```

**Comment by deadprogram** [comment]
Also `websocket/handler` and `webstatic`.

**Comment by scottfeldman** [comment]
Fixed with https://github.com/tinygo-org/net/pull/11
